2020-08-03 18:55:05,860 ERROR: Exception on /edit_profile [GET] [in c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\slavk\anotherblog\app\routes.py", line 85, in edit_profile
    form = EditProfileForm()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2020-08-03 18:56:17,716 INFO: Anotherblog startup [in C:\Users\slavk\anotherblog\app\__init__.py:43]
2020-08-03 18:56:25,582 ERROR: Exception on /edit_profile [GET] [in c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\slavk\anotherblog\app\routes.py", line 85, in edit_profile
    form = EditProfileForm()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2020-08-03 18:57:04,901 INFO: Anotherblog startup [in C:\Users\slavk\anotherblog\app\__init__.py:43]
2020-08-03 18:57:11,150 ERROR: Exception on /edit_profile [GET] [in c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\slavk\anotherblog\app\routes.py", line 85, in edit_profile
    form = EditProfileForm()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2020-08-03 19:03:45,454 INFO: Anotherblog startup [in C:\Users\slavk\anotherblog\app\__init__.py:43]
2020-08-03 19:03:52,018 ERROR: Exception on /edit_profile [GET] [in c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\slavk\anotherblog\app\routes.py", line 85, in edit_profile
    form = EditProfileForm()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2020-08-03 20:57:17,931 ERROR: Exception on /edit_profile [GET] [in c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\slavk\anotherblog\app\routes.py", line 85, in edit_profile
    form = EditProfileForm()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2020-08-03 21:01:06,057 INFO: Anotherblog startup [in C:\Users\slavk\anotherblog\app\__init__.py:43]
2020-08-03 21:01:11,731 ERROR: Exception on /edit_profile [GET] [in c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\slavk\anotherblog\app\routes.py", line 85, in edit_profile
    form = EditProfileForm()
  File "c:\users\slavk\anotherblog\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2020-08-08 14:38:06,614 INFO: Anotherblog startup [in C:\Users\slavk\anotherblog\app\__init__.py:43]
2020-08-08 14:41:09,033 INFO: Anotherblog startup [in C:\Users\slavk\anotherblog\app\__init__.py:43]
2020-08-09 21:22:16,480 INFO: Anotherblog startup [in C:\Users\slavk\anotherblog\app\__init__.py:43]
2020-08-09 23:57:19,843 INFO: Anotherblog startup [in c:\Users\slavk\anotherblog\app\__init__.py:43]
2020-08-11 21:02:04,448 INFO: Anotherblog startup [in c:\Users\slavk\anotherblog\app\__init__.py:43]
2020-08-12 22:27:49,215 INFO: Anotherblog startup [in C:\Users\slavk\anotherblog\app\__init__.py:45]
